import "../../groups/numeric" as numeric
import "subtraction" as subtraction

trait #Post_Decrement<ValueType, RetType> {
	fn inline #OP_POST_DECREMENT(ref: ValueType) -> RetType
}

impl<T> #Post_Decrement<ValueType: MutPlace<T>, RetType: T> where subtraction::#Subtraction<T, T, T> {
	fn inline #OP_POST_DECREMENT(value: ValueType) -> RetType {
		let old = value
		value = value - 1 to T
		old
	}
}

