import "std/lib" as std

fn main(argc: i32) -> i32 {
    func_1(0)
}

fn func_1(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_2(foo + 1)
}

fn func_2(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_3(foo + 1)
}

fn func_3(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_4(foo + 1)
}

fn func_4(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_5(foo + 1)
}

fn func_5(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_6(foo + 1)
}

fn func_6(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_7(foo + 1)
}

fn func_7(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_8(foo + 1)
}

fn func_8(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_9(foo + 1)
}

fn func_9(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_10(foo + 1)
}

fn func_10(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_11(foo + 1)
}

fn func_11(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_12(foo + 1)
}

fn func_12(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_13(foo + 1)
}

fn func_13(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_14(foo + 1)
}

fn func_14(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_15(foo + 1)
}

fn func_15(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_16(foo + 1)
}

fn func_16(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_17(foo + 1)
}

fn func_17(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_18(foo + 1)
}

fn func_18(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_19(foo + 1)
}

fn func_19(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_20(foo + 1)
}

fn func_20(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_21(foo + 1)
}

fn func_21(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_22(foo + 1)
}

fn func_22(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_23(foo + 1)
}

fn func_23(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_24(foo + 1)
}

fn func_24(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_25(foo + 1)
}

fn func_25(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_26(foo + 1)
}

fn func_26(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_27(foo + 1)
}

fn func_27(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_28(foo + 1)
}

fn func_28(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_29(foo + 1)
}

fn func_29(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_30(foo + 1)
}

fn func_30(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_31(foo + 1)
}

fn func_31(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_32(foo + 1)
}

fn func_32(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_33(foo + 1)
}

fn func_33(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_34(foo + 1)
}

fn func_34(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_35(foo + 1)
}

fn func_35(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_36(foo + 1)
}

fn func_36(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_37(foo + 1)
}

fn func_37(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_38(foo + 1)
}

fn func_38(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_39(foo + 1)
}

fn func_39(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_40(foo + 1)
}

fn func_40(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_41(foo + 1)
}

fn func_41(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_42(foo + 1)
}

fn func_42(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_43(foo + 1)
}

fn func_43(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_44(foo + 1)
}

fn func_44(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_45(foo + 1)
}

fn func_45(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_46(foo + 1)
}

fn func_46(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_47(foo + 1)
}

fn func_47(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_48(foo + 1)
}

fn func_48(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_49(foo + 1)
}

fn func_49(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_50(foo + 1)
}

fn func_50(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_51(foo + 1)
}

fn func_51(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_52(foo + 1)
}

fn func_52(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_53(foo + 1)
}

fn func_53(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_54(foo + 1)
}

fn func_54(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_55(foo + 1)
}

fn func_55(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_56(foo + 1)
}

fn func_56(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_57(foo + 1)
}

fn func_57(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_58(foo + 1)
}

fn func_58(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_59(foo + 1)
}

fn func_59(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_60(foo + 1)
}

fn func_60(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_61(foo + 1)
}

fn func_61(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_62(foo + 1)
}

fn func_62(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_63(foo + 1)
}

fn func_63(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_64(foo + 1)
}

fn func_64(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_65(foo + 1)
}

fn func_65(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_66(foo + 1)
}

fn func_66(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_67(foo + 1)
}

fn func_67(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_68(foo + 1)
}

fn func_68(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_69(foo + 1)
}

fn func_69(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_70(foo + 1)
}

fn func_70(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_71(foo + 1)
}

fn func_71(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_72(foo + 1)
}

fn func_72(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_73(foo + 1)
}

fn func_73(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_74(foo + 1)
}

fn func_74(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_75(foo + 1)
}

fn func_75(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_76(foo + 1)
}

fn func_76(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_77(foo + 1)
}

fn func_77(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_78(foo + 1)
}

fn func_78(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_79(foo + 1)
}

fn func_79(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_80(foo + 1)
}

fn func_80(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_81(foo + 1)
}

fn func_81(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_82(foo + 1)
}

fn func_82(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_83(foo + 1)
}

fn func_83(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_84(foo + 1)
}

fn func_84(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_85(foo + 1)
}

fn func_85(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_86(foo + 1)
}

fn func_86(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_87(foo + 1)
}

fn func_87(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_88(foo + 1)
}

fn func_88(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_89(foo + 1)
}

fn func_89(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_90(foo + 1)
}

fn func_90(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_91(foo + 1)
}

fn func_91(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_92(foo + 1)
}

fn func_92(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_93(foo + 1)
}

fn func_93(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_94(foo + 1)
}

fn func_94(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_95(foo + 1)
}

fn func_95(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_96(foo + 1)
}

fn func_96(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_97(foo + 1)
}

fn func_97(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_98(foo + 1)
}

fn func_98(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_99(foo + 1)
}

fn func_99(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_100(foo + 1)
}

fn func_100(foo: i32) -> i32 {
    let a: i32 = (2 + 222) * argc

    let b: i32 = a - argc

    let i: i32 = 0

    for i < b, i++ {
        i = i + 1
   }

    func_101(foo + 1)
}